apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-web-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      containers:
        - name: python-web-app
          image: kanika26/python-web-comm-file:latest
          ports:
            - containerPort: 5000  
---
apiVersion: v1
kind: Service
metadata:
  name: python-web-app-service
spec:
  selector:
    app: python-web-app
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 5000  
  type: NodePort  
